In [1]:
import csv
import math
import numpy as np
import pandas as pd
import time
import pickle
from scipy import stats
from sklearn import model_selection
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from scipy import interpolate
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn.model_selection import KFold
np.set_printoptions(formatter={'float_kind':'{:1}'.format})

In [6]:
data0 = pd.read_csv("images_v1.csv")
data_images=np.copy(data0.values)
data_images = np.delete(data_images, 0, 1)
print(data_images.shape)
print(data_images)

(48500, 1024)
[[138.0 137.0 211.0 ... 155.0 155.0 158.0]
 [159.0 149.0 161.0 ... 160.0 160.0 160.0]
 [167.0 161.0 161.0 ... 127.0 131.0 130.0]
 ...
 [247.0 244.0 246.0 ... 156.0 153.0 145.0]
 [249.0 255.0 255.0 ... 207.0 205.0 209.0]
 [116.0 117.0 118.0 ... 169.0 169.0 170.0]]


In [45]:
test_data0 = pd.read_csv("test_images.csv")
test_data_images=np.copy(test_data0.values)
test_data_images = np.delete(test_data_images, 0, 1)
print(test_data_images.shape)
print(test_data_images)

(9700, 1024)
[[106.0 93.0 59.0 ... 119.0 98.0 96.0]
 [235.0 232.0 231.0 ... 63.0 68.0 185.0]
 [154.0 150.0 151.0 ... 161.0 162.0 162.0]
 ...
 [136.0 203.0 202.0 ... 116.0 116.0 114.0]
 [128.0 25.0 31.0 ... 78.0 75.0 104.0]
 [165.0 158.0 152.0 ... 182.0 187.0 109.0]]


In [7]:
labels0 = pd.read_csv("labels.csv")
labels=np.copy(labels0.values)
labels = np.delete(labels, 0, 1)
labels=labels.reshape(-1)
print(labels.shape)
print(labels)

(48500,)
[7.0 2.0 9.0 ... 7.0 3.0 7.0]


In [46]:
#X_train, X_test, y_train, y_test = train_test_split(data_images, labels, test_size=0.20)

In [47]:
clf=RandomForestClassifier(n_estimators=100)
clf.fit(data_images,labels)
y_pred=clf.predict(test_data_images)
#print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [48]:
#sample['label']=y_pred.astype(int)
#print(sample['label'])
pd.DataFrame(y_pred.astype(int)).to_csv("pred_v0.csv")